{{- if and .Values.dockerRegistry.enabled (empty .Values.dockerRegistry.existingSecret) }}

apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-docker-registry-credentials
data:
  .dockerconfigjson: {{ include "imagePullSecret" .}}
type: kubernetes.io/dockerconfigjson

{{- end }}