apiVersion: v2

name: plane-enterprise
description: Meet Plane. An Enterprise software development tool to manage issues, sprints, and product roadmaps with peace of mind.

type: application

version: 1.3.3
appVersion: "1.13.0"

home: https://plane.so/
icon: https://plane.so/favicon/favicon-32x32.png
sources:
- https://github.com/makeplane/plane-ee
