{{- if .Values.services.opensearch.local_setup }}

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-opensearch
  labels:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-opensearch
spec:
  type: ClusterIP
  {{- if not .Values.services.opensearch.assign_cluster_ip }}
  clusterIP: None
  {{- end }}
  ports:
  - name: opensearch-{{ .Values.services.opensearch.servicePort }}
    port: {{ .Values.services.opensearch.servicePort }}
    protocol: TCP
    targetPort: 9200
  selector:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-opensearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-opensearch-wl
  {{- include "plane.labelsAndAnnotations" .Values.services.opensearch }}
spec:
  selector:
    matchLabels:
      app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-opensearch
  serviceName:  {{ .Release.Name }}-opensearch
  template:
    metadata:
      labels:
        app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-opensearch
    spec:
      {{- include "plane.podScheduling" .Values.services.opensearch }}
      containers:
      - image: {{ .Values.services.opensearch.image }}
        imagePullPolicy: {{ .Values.services.opensearch.pullPolicy | default "IfNotPresent" }}
        name: {{ .Release.Name }}-opensearch
        stdin: true
        tty: true
        envFrom:
          - secretRef:
              name: {{ if not (empty .Values.external_secrets.opensearch_existingSecret) }}{{ .Values.external_secrets.opensearch_existingSecret }}{{ else }}{{ .Release.Name }}-opensearch-secrets{{ end }}
              optional: false
          - configMapRef:
              name: {{ .Release.Name }}-opensearch-vars
              optional: false
        env:
          - name: discovery.type
            value: "single-node"
          - name: bootstrap.memory_lock
            value: "false"
          - name: OPENSEARCH_JAVA_OPTS
            value: "-Xms768m -Xmx768m"
          - name: OPENSEARCH_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-opensearch-vars
                key: OPENSEARCH_USERNAME
          {{- if .Values.extraEnv }}
          {{- toYaml .Values.extraEnv | nindent 10 }}
          {{- end }}
        command: ["/bin/bash", "/docker-entrypoint-init.d/create-user.sh"]
        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: pvc-{{ .Release.Name }}-opensearch-vol
          subPath: ''
        - mountPath: /docker-entrypoint-init.d
          name: {{.Release.Name}}-opensearch-init-script
      serviceAccount: {{ .Release.Name }}-srv-account
      serviceAccountName: {{ .Release.Name }}-srv-account
      volumes:
      - name: {{.Release.Name}}-opensearch-init-script
        configMap:
          name: {{ .Release.Name }}-opensearch-vars
          items:
          - key: create-user.sh
            path: create-user.sh
      serviceAccount: {{ .Release.Name }}-srv-account
      serviceAccountName: {{ .Release.Name }}-srv-account
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      namespace: {{ .Release.Namespace }}
      name: pvc-{{ .Release.Name }}-opensearch-vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.services.opensearch.volumeSize | default "5Gi" | quote }}
      storageClassName: {{ .Values.env.storageClass | quote }}
      volumeMode: Filesystem
      
{{- end }}

