apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-srv-account
{{- if .Values.dockerRegistry.enabled }}
imagePullSecrets:
{{- if .Values.dockerRegistry.existingSecret }}
  - name: {{ .Values.dockerRegistry.existingSecret }}
{{- else }}
  - name: {{ .Release.Name }}-docker-registry-credentials
{{- end }}
{{- end }}