apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-srv-account
  labels:
    {{- include "plane.labels" . | nindent 4 }}
{{- if .Values.dockerRegistry.enabled }}
imagePullSecrets:
  - name: {{ .Release.Name }}-docker-registry-credentials
{{- end}}
